name: Publish reports

on:
  workflow_run:
    workflows: ["Java CI with Gradle"]
    types:
      - completed

jobs:
  publish:
    name: Publish Test Report
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: ${{github.event.workflow_run.id}},
            });
            var linux_integration_test_reports_artifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "linux-integration-test-reports"
            })[0];
            var windows_test_reports_artifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "windows-test-reports"
            })[0];
            var macos_test_reports_artifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "macos-test-reports"
            })[0];
            var ubuntu_test_reports_artifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "ubuntu-test-reports"
            })[0];
            var download_linux_integration_test = await github.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: linux_integration_test_reports_artifact.id,
              archive_format: 'zip',
            });
            var download_ubuntu_test = await github.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: ubuntu_test_reports_artifact.id,
              archive_format: 'zip',
            });
            var download_windows_test = await github.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: windows_test_reports_artifact.id,
              archive_format: 'zip',
            });
            var download_macos_test = await github.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: macos_test_reports_artifact.id,
              archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/linux-integration-test-reports.zip', Buffer.from(download_linux_integration_test.data));
            fs.writeFileSync('${{github.workspace}}/ubuntu-test-reports.zip', Buffer.from(download_ubuntu_test.data));
            fs.writeFileSync('${{github.workspace}}/macos-test-reports.zip', Buffer.from(download_macos_test.data));
            fs.writeFileSync('${{github.workspace}}/windows-test-reports.zip', Buffer.from(download_windows_test.data));
      - run: |
          unzip linux-integration-test-reports.zip -d ${{github.workspace}}/linux-integration-test-reports/
          unzip ubuntu-test-reports.zip -d ${{github.workspace}}/ubuntu-test-reports/
          unzip macos-test-reports.zip -d ${{github.workspace}}/macos-test-reports/
          unzip windows-test-reports.zip -d ${{github.workspace}}/windows-test-reports/
      - name : Publish MacOS tests reports
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          report_paths: '${{github.workspace}}/macos-test-reports/**/TEST-*.xml'
          commit: ${{github.event.workflow_run.event.commit}}
      - name: Publish Windows tests reports
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          report_paths: '${{github.workspace}}/windows-test-reports/**/TEST-*.xml'
          commit: ${{github.event.workflow_run.event.commit}}
      - name: Publish Ubuntu tests reports
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          report_paths: '${{github.workspace}}/ubuntu-test-reports/**/TEST-*.xml'
          commit: ${{github.event.workflow_run.event.commit}}
      - name: Publish Integration tests reports
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          report_paths: '${{github.workspace}}/linux-integration-test-reports/**/TEST-*.xml'
          commit: ${{github.event.workflow_run.event.commit}}
